language: node_js
node_js: stable
branches:
  only:
  - hexo
cache:
  directories:
  - node_modules
before_install:
  - npm install -g hexo-cli
install:
  - npm install
before_script:
  - cd themes/sagiri
  - cd ../..
  - sed -i'' "s~github.com/JieRucker/blog.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/JieRucker/blog.git~" _config.yml
script:
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "Travis CI"
  - git config user.email "jrucker@163.com"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
env:
  global:
  - GH_REF: github.com/JieRucker/blog.git
  - secure: G2CX/TAFw5uKZZdAd6o+t1KHME2b3fic5pEXjBe2eBvU+skJ2HAstRgrbbJA5mCNyDlSW0uz40yVlGC4c3Js/t1hoCUN9PapCYN8LoF4nvsPZAcaPBRzwfyTLQwJfVDDm4grTjlXWgmz57A6EEQhO04nkEJraa76PoJoyLREvloXMr7/Usa9zFY5UPSH40rr3x/MHyKo8RpmaBmsxkpxceb8u0W3Hl+ezhHujEtjYrD57S2k0AKHOHT4mEZVaotmWW/Sc5MG52skn+7LBnjP/2nQ1U85SjqSiWqrkbuXMbw6VmCs+QkJL8YWqWzSa8udVlEuOxbGaIEzAIksKYIBeRox9ZUZO1s2u8MAH10D8OjFx5jHJ3jpEgFBESG7wP77Um3lwzm0xvv3wX/TOY56CRCuLQWteUTSmmPL1RkBLpIQADin4PqLxsZZAE8VhUkPrhnSFVXLSF5ORt6ke4d2KbjEr+H8UEKuAImGzcgamLMrsBN+tn0u/cQ/24rt4nRfz6ApqSue9wNFONeDULtswc/BR4mT9iq7e3cFkVSKBfgdksO7cfd5aQT8E1Jel5x+5KAHkC1tWFhqLoHpqwhLbUyrtbsZzMHSRFWqftu0iAyaVjD6+fzooAr7K0rzSQ4Z97ZTMfgAA3erR7Z/yj2Z4r/3nmG35ABP6Eh6CgiPNeM=
